### PR TITLE
Fix error in Theano when using GPU and TF (#19)

### PR DESCRIPTION
**Pull request by ghost**
The configuration of the GPU device in Theano is set if USE_TF is false and USE_GPU is true. Since USE_TF is only set to True when using AWS EC2, it's now also set as a parameter in the
run_experiment_list function.

To avoid the conflict with Theano when using TF and GPU, set both use_tf and use_gpu to True when calling run_experiment_list.

Also, to enable and disable GPU with TensorFlow, an if statement was inserted to make the GPU invisible when use_gpu=False.

### CODE REVIEW

**Review by ryanjulian — CHANGES_REQUESTED** [review]
Can you update the documentation with this information?

https://github.com/ryanjulian/rllab/blob/integration/docs/user/experiments.rst

**Comment by ghost** [comment]
It seems instrument .py had not been checked by Travis before and it was not properly formatted. Last two commits solve that.
The documentation was updated @ryanjulian. Please review again.

**Review by ryanjulian — APPROVED** [review]
LGTM

For instrument.py, do we need to add `use_tf` flags or logic to the EC2/kube/docker cases too?

**Review by eric-heiden — APPROVED** [review]

**Comment by ryanjulian** [comment]
Please don't merge until my question is addressed. I don't want to break docker/ec2/kubernetes support.

**Comment by ghost** [comment]
EC2, kube and docker only check the flag use_gpu for its logic. The use_tf flag does not break any of those running modes, however, it was added to the environment variables that are passed to the docker container (local or in EC2), in case it's required.

**Pull request merged**
