### PR TITLE
Support std_share_network in all GaussianMLP* classes

### PR DESCRIPTION
**Pull request by CatherineSue**
Implement std_share_network architecture in the GaussianMLP*
classes of TensorFlow.

The std_share_network creates a single neural net with output
length of 2 * action_dimension. The first half output params
are the means params, and the second half params are the
log_std params.

As a result, the GaussianMLP* classes can support a new
architecture.

Refer to: #44

### CODE REVIEW

**Comment by ryanjulian** [comment]
I think this also applies to
* GaussianGRUPolicy
* GaussianLSTMPolicy
* GaussianMLPRegressor

The GRU and LSTM policies are recurrent, so the implementation might look a little different.

**Review by ryanjulian — CHANGES_REQUESTED** [review]
This looks good but, but I think changes are also needed in more classes. See my comment above.

**Comment by ryanjulian** [comment]
This is looking great. Were you able to test training all of these policies with `std_share_network=True`?

**Comment by ryanjulian** [comment]
You can use https://github.com/ryanjulian/rllab/blob/integration/sandbox/rocky/tf/launchers/trpo_cartpole_recurrent.py to test the recurrent policies and https://github.com/ryanjulian/rllab/blob/integration/sandbox/rocky/tf/launchers/trpo_cartpole.py to test the non-recurrent policy.

Comment back when the successfully train, and this will be ready to go!

**Comment by CatherineSue** [comment]
Successfully tested training with both non-recurrent policy and recurrent policies.

**Review by ryanjulian — APPROVED** [review]

**Review by jonashen — APPROVED** [review]

**Pull request merged**
