### PR TITLE
Fix error in Theano when using GPU and TF

### PR DESCRIPTION
**Pull request by ghost**
The configuration of the GPU device in Theano is set if USE_TF is false
and USE_GPU is true. Since USE_TF is only set to True when using AWS
EC2, it's now also set as a parameter in the run_experiment_list
function.

To avoid the conflict with Theano when using TF and GPU, set both use_tf
and use_gpu to True when calling run_experiment_list.

to enable and disable GPU with TensorFlow, an if statement was inserted
to make the GPU invisible when use_gpu=False.

Also, an environment variable for use_tf for non-local modes such as
local_docker or EC2 was added if it's required to switch between Theano
and TensorFlow.

Finally, the corresponding documentation was added in experiments.rst.

### CODE REVIEW

**Comment by ghost** [comment]
Reviewers,
This is **almost** the same change as #63, but I mistakenly pushed a merge commit in the integration branch and a revert had to be applied, so I cannot re-merge that change.
The difference with this new change is that it does not apply the PEP8 formatting as in #63 based on the comments made by Ryan in #66, and that's why Travis CI fails.
Sorry for the inconvenience.

**Review by ryanjulian — APPROVED** [review]

**Comment by ryanjulian** [comment]
LGTM, waiting for second review.

@gonzaiva can you wrap your commit messages to 72 characters, per the [guidelines](https://chris.beams.io/posts/git-commit/)? I think this is wrapped to 63-64 chars.

I can help you setup your editor to show a right margin marker at 72 chars to make this easier.

**Review by hejia-zhang — APPROVED** [review]

**Comment by ryanjulian** [comment]
CI build is failing. Is there a syntax error?

**Comment by ghost** [comment]
@ryanjulian yes, as I mentioned in my previous comment.

**Comment by ghost** [comment]
@ryanjulian the only way to make CI work is by formatting implement.py with YAPF, but as you mention in #66, that will be done in its own pull request. How can we bypass CI in this case?
I also set the text width of my editor to 72 characters.

**Comment by ryanjulian** [comment]
The reason I am worried is that the CI failure is unrelated to improper formatting. The formatter crashes before it can even decide that the format is wrong.

```sh
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/opt/python/3.5.2/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/opt/python/3.5.2/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/opt/python/3.5.2/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=12, value=',', context=('', (982, 34))
```

**Comment by ryanjulian** [comment]
Can you please try it on your machine and see if you can replicate the crash?

**Comment by ghost** [comment]
That's also related to formatting. The context in the ParseError mentions the line and the value (',') of what happened. Please see https://github.com/ryanjulian/rllab/pull/63/commits/66baf5d1545f8f7edd3aed6565590ab7e1ef5c87
Do I push this fix in this request as well?

**Comment by ryanjulian** [comment]
Yes, please make the CI fail *only* on YAPF formatting differences first. It seems that some version of Python does not like trailing commas?

Once the CI is only failing with YAPF errors, I will force merge it.

**Pull request merged**
