### PR TITLE
Tensorboard Support

### PR DESCRIPTION
**Pull request by cjcchen**
This PR adds Tensorboard Support.

>A folder can be set to save tensorboard data.
>A step key can be set to make your own step key in data, and it also enables users to continue their training and show the data on tensorboard.

data can be showed by tensorboard:
>tensorboard --logdir="data dir"

data example:
image

### CODE REVIEW

**Review by ryanjulian — COMMENTED** [review]
Looks great! It looks like you need to rebase this cleanly on integration to get rid of the dm_control commits.

```sh
git rebase -i integration
```

**Comment by ryanjulian** [comment]
You need to add tensorboard to environment.yml

**Comment by cjcchen** [comment]
Tensorflow package includes tensorboard.
But I saw from the environment.yml, the version of tensorflow is 1.0. Is it too old?

**Comment by ryanjulian** [comment]
```sh
rjulian@nyquist:~/code$ mkdir test_tb
rjulian@nyquist:~/code$ cd test_tb
rjulian@nyquist:~/code/test_tb$ git clone git://github.com/cjcchen/rllab.git
Cloning into 'rllab'...
remote: Counting objects: 1550, done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 1550 (delta 75), reused 70 (delta 37), pack-reused 1439
Receiving objects: 100% (1550/1550), 1.55 MiB | 0 bytes/s, done.
Resolving deltas: 100% (859/859), done.
Checking connectivity... done.
rjulian@nyquist:~/code/test_tb$ cd rllab/
rjulian@nyquist:~/code/test_tb/rllab$ export PYTHONPATH=`pwd`
rjulian@nyquist:~/code/test_tb/rllab$ git checkout tensorboard
rjulian@nyquist:~/code/test_tb/rllab$ vim environment.yml 
rjulian@nyquist:~/code/test_tb/rllab$ conda env create -f environment.yml 
rjulian@nyquist:~/code/test_tb/rllab$ conda activate rllab3-tb1
(rllab3-tb1) rjulian@nyquist:~/code/test_tb/rllab$ which tensorboard
/home/rjulian/miniconda2/envs/rllab3-tb1/bin/tensorboard
(rllab3-tb1) rjulian@nyquist:~/code/test_tb/rllab$ tensorboard --version
Traceback (most recent call last):
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/tensorboard/main.py", line 30, in <module>
    from tensorboard import default
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/tensorboard/default.py", line 35, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 27, in <module>
    from tensorboard import plugin_util
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/tensorboard/plugin_util.py", line 21, in <module>
    import bleach
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/bleach/__init__.py", line 8, in <module>
    from bleach.linkifier import (
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/bleach/linkifier.py", line 6, in <module>
    from html5lib.filters.base import Filter
ImportError: No module named 'html5lib.filters.base'
(rllab3-tb1) rjulian@nyquist:~/code/test_tb/rllab$ tensorbord --logdir=data
tensorbord: command not found
(rllab3-tb1) rjulian@nyquist:~/code/test_tb/rllab$ tensorboard --logdir=data
Traceback (most recent call last):
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/tensorboard/main.py", line 30, in <module>
    from tensorboard import default
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/tensorboard/default.py", line 35, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 27, in <module>
    from tensorboard import plugin_util
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/tensorboard/plugin_util.py", line 21, in <module>
    import bleach
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/bleach/__init__.py", line 8, in <module>
    from bleach.linkifier import (
  File "/home/rjulian/miniconda2/envs/rllab3-tb1/lib/python3.5/site-packages/bleach/linkifier.py", line 6, in <module>
    from html5lib.filters.base import Filter
ImportError: No module named 'html5lib.filters.base'
```

**Comment by ryanjulian** [comment]
You somehow ended up with the dm_control commits in your branch again. It is because your `integration` branch is unclean (you should keep it the same as mine). 

## For future PRs
Reference on how to develop with a feature branch/rebase workflow: 
https://gist.github.com/markreid/12e7c2203916b93d23c27a263f6091a0

## To fix your current PRs

### Move dm_control into a feature branch
```sh
cd rllab
git checkout integration
git checkout -b dm_control
git push origin dm_control # change your pull request to point to ryanjulian/integration <-- cjcchen/dm_control
```
### Make integration track upstream (my repo, NEVER develop in integration)
```sh
git checkout integration
git remote add ryanjulian git@github.com:ryanjulian/rllab.git
git fetch ryanjulian
git reset --hard ryanjulian/integration
git push -f origin integration
```
### Rebase your dm_control feature branch onto the upstream integration (always do this before pull request)
```sh
git checkout dm_control
git rebase -i ryanjulian/integration # delete commits related to tensorboard, you do not usually need -i (just for removing commits)
git push -f origin dm_control
```

### Rebase your tensorboard feature branch onto the upstream integration (always do this before pull request)
```sh
git checkout tensorboard
git rebase -i ryanjulian/integration # delete commits related to dm_control, you do not usually need -i
git push -f origin tensorboard
```

**Comment by ryanjulian** [comment]
Will approve once the CI passes and the dm_control commits are removed.

**Comment by cjcchen** [comment]
When I run rebase, it seems not work......

**Comment by ryanjulian** [comment]
What happens during the rebase?

**Pull request closed without merging**
